# Generated by Django 3.0.5 on 2020-04-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='IMDB_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'ACTION'), ('DRAMA', 'DRAMA'), ('CRIME', 'CRIME'), ('COMEDY', 'COMEDY'), ('ROMANCE', 'ROMANCE'), ('MYSTERY', 'MYSTERY')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('HN', 'Hindi'), ('FR', 'French'), ('CH', 'Chineese'), ('KO', 'Korean')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(null=True, upload_to='movies'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
