# Generated by Django 3.0.5 on 2020-04-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200412_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='carousal_pic1',
            field=models.ImageField(blank=True, null=True, upload_to='movies'),
        ),
        migrations.AddField(
            model_name='movie',
            name='carousal_pic2',
            field=models.ImageField(blank=True, null=True, upload_to='movies'),
        ),
        migrations.AddField(
            model_name='movie',
            name='carousal_pic3',
            field=models.ImageField(blank=True, null=True, upload_to='movies'),
        ),
    ]
