# Generated by Django 3.0.5 on 2020-04-13 01:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200412_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_link',
            name='link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='download_link',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
