# Generated by Django 3.0.5 on 2020-04-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200413_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='IMDB_rating',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
