# Generated by Django 3.0.5 on 2020-04-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200413_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='IMDB_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='carousal_pic1',
            field=models.ImageField(null=True, upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='carousal_pic2',
            field=models.ImageField(null=True, upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='carousal_pic3',
            field=models.ImageField(null=True, upload_to='movies'),
        ),
    ]
