# Generated by Django 3.0.5 on 2020-04-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20200413_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
